### ISSUE TITLE
Librarian-puppet can't find puppet/archive

### ISSUE THREAD

**Issue by lord2800** [voxpupuli/puppet-rundeck#131]
It seems the dependency is actually named [`nanliu/archive`](https://forge.puppetlabs.com/nanliu/archive) on puppetlabs forge. Maybe I'm looking at the wrong one though?

**Comment by mkrakowitzer** [comment]
We need to release this module in using the puppet namespace, nanliu is the previous namespace.

**Comment by igalic** [comment]
gosh, yes.
@mkrakowitzer do you wanna start with adding it to msync :P

**Comment by jamielennox1** [comment]
When is this due to be released into the puppet forge?

**Comment by jyaworski** [comment]
@igalic is https://github.com/puppet-community/puppet-archive/ even on the forge? That's what it is referencing. Are _any_ of the community modules on the forge?

**Comment by igalic** [comment]
@jyaworski yes, there are many community on the forge under the /puppet namespace.

but puppet-archive isn't yet. it's still choking on https://github.com/maestrodev/puppet-blacksmith/issues/23

**Comment by jyaworski** [comment]
This got fixed at some point.
