### ISSUE TITLE
HTTPS/SSL Support

### ISSUE THREAD

**Issue by FireDrunk** [voxpupuli/puppet-rundeck#176]
Is there any support for managing the HTTPS/SSL configuration planned?

According to the docs settings should be set in server/config/ssl.properties and the respective keystores should contain proper certificates.

Is it possible to add support for templating this file in the module?

Would be much appreciated!

**Comment by jyaworski** [comment]
@FireDrunk I have something going on at #155, but it's taking a bit. Please add input there.

**Comment by wyardley** [comment]
I believe SSL support is now implemented, let me know if there's still something lacking.
