### ISSUE TITLE
No code to manage cacert (ldaps) and rundeck's private key

### ISSUE THREAD

**Issue by SydOps** [voxpupuli/puppet-rundeck#182]
To active ldaps, we need manually import certificate to `/etc/rundeck/ssl/truststore` or `$JAVA_HOME/lib/security/cacerts`

To re-product rundeck server, we need manage its private key, with this feature, we can rebuild rundeck server without replace public key on all clients.

**Comment by SydOps** [comment]
There is an exist forge module [puppetlabs/java_ks](https://forge.puppetlabs.com/puppetlabs/java_ks) which can be used to input `cacert`. So not sure this should be managed by `puppet-rundeck` module or `puppetlabs/java_ks`

**Comment by dalisch** [comment]
These are 2 separate issues, but our teams have problems with both.

**Comment by jyaworski** [comment]
I have an open PR that's a bit stale at #155.

**Comment by SydOps** [comment]
@dalisch 

Thanks. I currently work on the code with another forge module https://forge.puppetlabs.com/puppetlabs/java_ks with totally seperate codes. Then I saw @jyaworski 's reply, seems he already used that forge module, plus he merged codes into `puppet-rundeck` directly. It should be fine, if his changes can be merged. 

For private key, my environment is in aws, so I upload the private key in a s3 bucket and copy it if need rebuild rundeck server in the future, but this is not a generic way. 

 I am happy if you can work out to manage rundeck private key.
