### ISSUE TITLE
Rundeck private key id_rsa incorrectly set to mode '0640'

### ISSUE THREAD

**Issue by dalisch** [voxpupuli/puppet-rundeck#196]
The private key should never be visible to anyone except the user itself (ie: mode '0600').  The permissions are now be overridden to '0640', resulting in an error something like:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0640 for '/var/lib/rundeck/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /var/lib/rundeck/.ssh/id_rsa
```

The permissions for id_rsa need to be preserved as '0600'.

**Comment by danifr** [comment]
What about adding something like this?
```puppet
  file { $rdeck_home:
    ensure  => directory,
    recurse => true,
    owner   => $user,
    group   => $group,
    mode    => '0640',
  }~>
  file { $rundeck::params::framework_config['framework.ssh.keypath']:
    owner   => $user,
    group   => $group,
    mode    => '0600',
  }
```

**Comment by dalisch** [comment]
This seems to work, thanks - I'll use that for now.  I'm also adding a resource default as the owner/group/mode is repeated several times in the manifests.

**Comment by jyaworski** [comment]
We have an open PR against rundeck proper to fix this.

**Comment by dalisch** [comment]
which one?

**Comment by jyaworski** [comment]
https://github.com/rundeck/rundeck/issues/1521

**Comment by dalisch** [comment]
Thanks @jyaworski , but these are actually separate issues (although the underlying with SSL is the same).  This issue refers to a bug that was injected in the puppet-rundeck codebase, and I have a PR to fix that now: [PR#202](https://github.com/voxpupuli/puppet-rundeck/pull/202) and has to do with the file permissions of the private key of the 'rundeck' user itself in /var/lib/rundeck.  [rundeck/rundeck#1521](https://github.com/rundeck/rundeck/issues/1521) is an issue with Rundeck itself in how it manages private keys in the keystore facility.

**Comment by dalisch** [comment]
closed [PR#202](https://github.com/voxpupuli/puppet-rundeck/pull/202) (not merged), will open up another later.

**Comment by dalisch** [comment]
https://github.com/voxpupuli/puppet-rundeck/pull/204

**Comment by bdwyertech** [comment]
I've been looking at this as well...  I'm going to make a cron that runs the below.
```
chown -R rundeck:rundeck /var/lib/rundeck/var/storage/content && find /var/lib/rundeck/var/storage/content \! -perm 600 -type f -exec chmod 0600 "{}" \;
```
