### ISSUE TITLE
rdeck_base is documented but not in the param list

### ISSUE THREAD

**Issue by MelanieGault** [voxpupuli/puppet-rundeck#197]
Hi,

the param rdeck_base is in the doc, and in the header of the init.pp, but it's not present in the init.pp param list.
I did not take the time to look how do the module use it, but we can remove it from init.pp and README or add it to init.pp.

Thanks.
Mélanie.

**Comment by jyaworski** [comment]
We should add it to init.pp. This module has a lot of these mistakes.

**Comment by wyardley** [comment]
Config actually seems to pick up `rdeck_base` from `$framework_config['rdeck.base']` anyway! Seems to me like it should be one or the other, either params should accept the param from rdeck_base, and that should be used throughout (including in `rundeck::params::framework_config => rdeck.base`), or that it should be removed, and that users should override it using `framework_config`.

@juniorsysadmin @bastelfreak: thoughts on this?
