### ISSUE TITLE
groupdel: cannot remove the primary group of user 'rundeck'

### ISSUE THREAD

**Issue by danifr** [voxpupuli/puppet-rundeck#199]
I will try to simplify a bit this code https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/install.pp#L71 to try to get rid of puppet errors when using configuring user/group != rundeck.

```
Puppet  Could not delete group rundeck: Execution of '/usr/sbin/groupdel rundeck' returned 8: groupdel: cannot remove the primary group of user 'rundeck'
/Stage[main]/Rundeck::Install/Group[rundeck]/ensure     change from present to absent failed: Could not delete group rundeck: Execution of '/usr/sbin/groupdel rundeck' returned 8: groupdel: cannot remove the primary group of user 'rundeck'
```

Basically it needs a couple of runs to remove any trace of rundeck user & group.
I will try to add a dependency so it first removes the user and then the group.

**Comment by jyaworski** [comment]
Do we actually want to remove the rundeck user?

**Comment by danifr** [comment]
> Do we actually want to remove the rundeck user?

Probably not.

Anyway if for some reason we want to ensure that it gets removed, I was thinking to change what we have to something more like:
```puppet
  ensure_resource('group', $group, { 'ensure' => 'present' } )
  ensure_resource('user', $user, { 'ensure' => 'present', 'groups' => [$group] } )
  if $user != 'rundeck' {
    user { 'rundeck':
      ensure => absent,
    }
  }
  if $group != 'rundeck' {
    group { 'rundeck':
      ensure  => absent,
      require => User['rundeck'],
    }
  }
```

I've been using this patch for a couple of days and it fixes this issue.

**Comment by wyardley** [comment]
I reworked this a bit in #351 now that `user_id` and `group_id` are optional integers, but I think there's still room for improvement. I was able to reproduce some ordering issues.
Also, if it tries to change or delete the user while rundeckd is running, there will also be some errors, I think.

**Comment by wyardley** [comment]
If you can try with 5.0.0 once it gets out, would be nice to hear some feedback.
I think, though, that there are also problems removing the user while rundeck is running, so that may be hard to work around.

**Comment by danifr** [comment]
Sorry for the laaaateee response. I think we can close this one. Thanks @wcooley :)
