### ISSUE TITLE
Insecure downloading of packages

### ISSUE THREAD

**Issue by rraptorr** [voxpupuli/puppet-rundeck#205]
Class rundeck::install downloads Debian rundeck package to /tmp with known and predictable name (like /tmp/rundeck-2.6.4.deb).

This opens a security hole, as any user on the system can write to /tmp and create .deb file that will be installed by the module as soon as system administrator tries to update rundeck version using this module.

Files should be downloaded to /tmp/ with unpredictable names or be downloaded to someplace that is not writable by users.

**Comment by igalic** [comment]
and we're not verifying the downloaded .deb file after downloading it?

**Comment by rraptorr** [comment]
Downloaded .deb file is simply given to 'dpkg -i' so I don't see any verification, unless I've missed something.

**Comment by igalic** [comment]
in the case of yum, we add the repo, and [disable the gpg check](https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/install.pp#L40)

IMO, we should add the repo in both cases, and disable it in ***no*** case.

**Comment by jyaworski** [comment]
@rraptorr I'm working on a solution for this. No ETA sadly. A lot of work needs to be done to even get to this point. Please see #203. It's a massive refactor.

**Comment by cy4n** [comment]
is this still an issue? 
the default debian installation has been changed to bintray apt installation with apt-key import in #308
as @igalic posted gpg check is disabled by default, but one should be able to enable it in configuration.
aside of this, bintray serves packages over httpS, so the issue is not as bad as the old http .deb download imho.

**Comment by wyardley** [comment]
The RedHat repo does have `gpgcheck=0`
https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/install.pp#L43

We should probably have the module ship the key or retrieve it (https://bintray.com/rundeck)

Looks like Debian now specifies the key for the repo:
https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/install.pp#L58-L60

**Comment by wyardley** [comment]
Closing via #358. It's now also more configurable.
