### ISSUE TITLE
Change "required" to "sufficient" in _auth_file.erb as workaround for rundeck bug

### ISSUE THREAD

**Issue by remixtj** [voxpupuli/puppet-rundeck#206]
Since there is a bug not fixed yet in rundeck (see https://github.com/rundeck/rundeck/issues/1111 ), file template should be patched to include the workaround.

I personally tested the workaround and works, but since I'm enforcing configurations via puppet, I had to disable file based auth.

**Comment by igalic** [comment]
@remixtj would you like to provide a patch for this? (too;)

**Comment by remixtj** [comment]
Done, see #211
