### ISSUE TITLE
Add possibility to change loglevel for some rundeck logs

### ISSUE THREAD

**Issue by remixtj** [voxpupuli/puppet-rundeck#207]
I encountered a filesystem full issue last day because of the configuration present in the log4j template.:

With this entry:
```
log4j.logger.com.dtolabs.rundeck.core.authorization=info, audit
```

I had, after a run of ~250 jobs, a _rundeck.audit.log_ file of **8GB(!)**. This is maybe due to my acl policies denying certain functions to users that were working on rundeck interface.

**Comment by igalic** [comment]
@remixtj would you like to provide a patch for this?
I'd also add rotation for logs (which log4j & company also support)

**Comment by remixtj** [comment]
The problem is not rotating logs. The log is correctly rotated on daily basis, but grows to that size in a single day.
