### ISSUE TITLE
Support for SSL Terminated Proxy

### ISSUE THREAD

**Issue by richardraseley** [voxpupuli/puppet-rundeck#225]
I suppose this is more of a feature request, but I'd be interested in support for terminating SSL at a proxy, as outlined in http://rundeck.org/docs/administration/configuring-ssl.html#using-an-ssl-terminated-proxy.

I validate that adding `-Drundeck.jetty.connector.forwarded=true` did the trick.

**Comment by jyaworski** [comment]
Do you mean something like what Nginx does? I run mine on http, but clients connect to nginx on https.

**Comment by richardraseley** [comment]
Nginx can provide SSL termination and reverse proxy capability, but I am using HAProxy specifically.

**Comment by ak0ska** [comment]
I think this is currently possible by providing your own template via the [rundeck_profile_template](https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/init.pp#L181) parameter. You can copy the template from the module, add the extra switch(es) you need, and tell the module to use your own template instead of the built-in one.

**Comment by richardraseley** [comment]
@ak0ska - You appear to be correct, thank you.

I am not sure if this feature request would still be useful more generally as part of the module. I will leave to others to judge.

**Comment by darrenk13** [comment]
could we update the template to something like this?

```
--- modules/rundeck/templates/profile.erb	(revision xxxxxx)
+++ modules/rundeck/templates/profile.erb	(working copy)
@@ -27,6 +27,9 @@
 <%- if !(@kerberos_realms.empty?) -%>
 -Djava.security.krb5.conf=<%= @properties_dir %>/krb5.conf \
 <%- end -%>
+<%- if @jetty_connector_forward -%>
+-Drundeck.jetty.connector.forwarded=<%= @jetty_connector_forward %> \
+<%- end -%>
 -Dloginmodule.name=authentication"
 
 <%- if @server_web_context -%>
```


the variable would need to be defined and verified that it was a boolean.  This would allow people to use this in hiera and not create a new template file. 

Another option would be to have a variable to allow adding arbitrary strings to the RDECK_JVM variable in that template.  That would help future proof in case there are any other values that could be used there.

**Comment by jyaworski** [comment]
@darrenk13 we're open to PRs if you want to file one. I believe someone proposed something like that previously.

**Comment by dandunckelman** [comment]
@richardraseley @jyaworski I believe this can be closed, as it can be implemented in this way:

```
class { '::rundeck':
    jvm_args => '-Drundeck.jetty.connector.forwarded=true',
}
