### ISSUE TITLE
SSL truststore path is incorrect

### ISSUE THREAD

**Issue by duffrecords** [voxpupuli/puppet-rundeck#232]
The SSL truststore path in templates/profile.erb is set to the wrong location, which makes rd-jobs unable to connect.  See the following issue:

[https://github.com/rundeck/rundeck/issues/507](url)

It could be fixed like this:
`-export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"
+export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=<%= @properties_dir %>/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"`

**Comment by zlanyi** [comment]
Hi, this issue fixed in pull request here: https://github.com/voxpupuli/puppet-rundeck/pull/261

Cheers
Zoltan
