### ISSUE TITLE
Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppetx/rundeck/acl

### ISSUE THREAD

**Issue by nferragu** [voxpupuli/puppet-rundeck#235]
Hi,

I get the following error:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppetx/rundeck/acl on node nodename
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I have only declared the rundeck module without any parameter.
All the modules from the .fixtures.yml are deployed on my Puppet master (v 3.8.x).
The puppet node is a CentOS 7 which seems to be not supported from the README.

The files `/var/lib/puppet/lib/puppet/parser/functions/validate_rd_policy.rb` and `/var/lib/puppet/lib/puppetx/rundeck/acl.rb` have been synced on the node.

By the way, @chad-upton got the same [error](https://github.com/voxpupuli/puppet-rundeck/pull/146) but he got through this by running a `puppet check` (which I don't know what it is exactly - a `parser validate` and a `lint` have been run on every manifest).

Please help as it seems related to the two ruby functions above (I am not a Ruby expert).

Regards

**Comment by jyaworski** [comment]
@nferragu try doing a full stop and start of the master. Also, make sure the server and agent are pointed to the same environment.

**Comment by nferragu** [comment]
Hi,

Thanks for your response. Here is what I've managed to do but without success :

On puppet server : 
``systemctl restart puppetserver``

On my node : 
`puppet agent -t --no-noop --environment=rundeck`
`Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppetx/rundeck/acl on node mynode.fqdn.dom
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

Though, I've deployed my module on only one environment.

**Comment by nferragu** [comment]
Hello,

The issue seems to be corrected in github. Thus, there's a Puppetforge lacks of sync.

The problem was in : ` /var/lib/puppet/lib/puppet/parser/functions/validate_rd_policy.rb `
Replacing : ` require 'puppetx/rundeck/acl' `
With : `require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'puppetx', 'rundeck', 'acl.rb')) `
was successful too.

Your github contains : `require File.expand_path('../../../../puppetx/rundeck/acl', __FILE__) `

Thanks for your attention,
