### ISSUE TITLE
Metadata declare dependency of version 1.0.3 of puppetlabs-inifile but it doesn't contain create_ini_settings

### ISSUE THREAD

**Issue by jairojunior** [voxpupuli/puppet-rundeck#268]
metadata.json should point to version 1.3.0

https://github.com/voxpupuli/puppet-rundeck/blob/5083a17d184599eba1a09da752a68183866b25ff/manifests/config/project.pp#L196

**Comment by bastelfreak** [comment]
thanks, merged the PR.
