### ISSUE TITLE
/etc/rundeck/profile format changed with rundeck-2.6.10

### ISSUE THREAD

**Issue by grafjo** [voxpupuli/puppet-rundeck#284]
Hi,

the format of `/etc/rundeck/profile` changed with the current version of rundeck / rundeck-2.6.10. The change was done here https://github.com/rundeck/rundeck/pull/2030/commits/7ebbf41dbbbebdc940ac373870fbf45b75fbdd6d

rundeck won't start on rhel / centos machines again.

Issues getting rundeck up and running again are discussed here https://github.com/rundeck/rundeck/issues/2164

**Comment by danifr** [comment]
Fixed in 2.6.11, should we close this issue?

**Comment by grafjo** [comment]
@danifr maybe we sould open this issue as with 2.7 there is a /etc/sysconfig/rundeck file now
