### ISSUE TITLE
More intelligent, easier SSL setup

### ISSUE THREAD

**Issue by ak0ska** [voxpupuli/puppet-rundeck#30]
The module ignores the ssl_enabled setting when configuring the framework properties, and the grails server url. In both cases it uses http and port 4440, instead of switching to https 4443 when ssl is enabled.

**Comment by jyaworski** [comment]
I may take a look at this soon.

**Comment by wyardley** [comment]
I think this is now handled in at least a semi-intelligent way.
I made some additional fixes in #356, though there are probably some use cases this still doesn't handle perfectly. For example, it would be nice to allow overriding  `framework.server.url` in the case where one wants it to be different from the setting of `ssl_port`. Still, going to close this one out.
