### ISSUE TITLE
Could not autoload puppet/parser/functions/validate_rd_policy:  Syntax Error, unexpected ':'

### ISSUE THREAD

**Issue by andybCDL** [voxpupuli/puppet-rundeck#311]
Hi folks

Trying to configure a very basic install of rundeck with puppet. I'm getting this error;

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_rd_policy: /etc/puppet/environments/sa_dev/modules/rundeck/lib/puppet/parser/functions/validate_rd_policy.rb:7: syntax error, unexpected ':', expecting ')'
...tion(:validate_rd_policy, doc: <<-'ENDHEREDOC') do |args|
                              ^ on node XXXXXXXXXXXX
Warning: Not using cache on failed catalog

Using version 3.3.0 of the module.

Any ideas?

**Comment by bastelfreak** [comment]
Hi @andybCDL. You are using a legacy ruby version, probably 1.8.7. We dropped support for it  with the 3.0 release. the 2.3.0 release is the last one that supports that old ruby version. Feel free to join our IRC channel #voxpupuli on freenode if you have any questions about upgrading your ruby or Puppet version. Newer AIO packages ship puppet 4 with a bundled ruby version.

**Comment by andybCDL** [comment]
Thanks @bastelfreak , yes the version of ruby on our puppet master is 1.8.7, sadly I can't upgrade it as its a shared master. I tried rolling back to 2.3.0 but it seems that version is not available via the puppetforge? 2.2.0 seems to have similar issues with the validate_rd_policy.rb


Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppetx/rundeck/acl on node dev-sdc-rdk001.cheshdatasys.co.uk
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
