### ISSUE TITLE
Add support for Rundeck v2.7.x

### ISSUE THREAD

**Issue by dandunckelman** [voxpupuli/puppet-rundeck#315]
Nike!

**Comment by af6140** [comment]
@dandunckelman looks like voxpupuli works through a community triage google hangout event. They even has a community-triage repo.

**Comment by dandunckelman** [comment]
@af6140 oh interesting.  I looked thru the `CONTRIBUTING` doc, but that's not detailed there.  Where'd you find that info?

**Comment by af6140** [comment]
@dandunckelman  check commit log of https://github.com/voxpupuli/community-triage

**Comment by dandunckelman** [comment]
@af6140 thanks!

**Comment by af6140** [comment]
@dandunckelman  man you are fast.

**Comment by dandunckelman** [comment]
@af6140 Ha, I'm working right now so email notifications catch my eye.
