### ISSUE TITLE
Rundeck service not starting

### ISSUE THREAD

**Issue by ibaboo** [voxpupuli/puppet-rundeck#319]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.1
- Ruby: ruby-2.1.0
- Distribution: CentOS Linux release 7.3.1611
- Module version: 3.3.0

## How to reproduce (e.g Puppet code you use)
class profile::rundeck {
  include '::rundeck'
}

## What are you seeing
Rundeck does not start
## What behaviour did you expect instead
Rundeck should start
## Output log
Nothing being logged in logs
## Any additional information you'd like to impart

Both puppet and yum install rundeck 2.8.2-1.31.GA. If I install rundeck with yum it works fine. I did find that the variable  rundeckd is set in the /etc/rundeck/profile when installed with yum. However when installed with puppet there is no reference to rundeckd in /etc/rundeck/profile. If I added the values for rundeckd on the puppet installation it does start.

**Comment by bastelfreak** [comment]
Hi @ibaboo, this should be fixed with https://github.com/voxpupuli/puppet-rundeck/pull/323

**Comment by Prannon** [comment]
Any chance you can commit this update to version 3.3.0 on puppet forge? If not, can you leave a comment noting the availability of this fix here?
