### ISSUE TITLE
file-based authentication broken for rundeck 2.7 and up

### ISSUE THREAD

**Issue by shamil** [voxpupuli/puppet-rundeck#325]
### How to reproduce

set `package_ensure` to `2.7.3`

### What are you seeing

Since rundeck 2.7, jetty was upgraded to 9.x, which means jaas module class for file-based authentication needs to be changed 

old value: `org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule`
new value: `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule`

[more info](https://github.com/rundeck/rundeck/blob/master/docs/en/upgrading/upgrading.md#jetty-embedded-server-was-upgraded-to-90x)

**Comment by cy4n** [comment]
this will be fixed in 571e90449ba0db72f2003e728823ce88035224a2 for rundeck 2.7 and when it gets released this will break support rundeck 2.6 and earlier

**Comment by cy4n** [comment]
this works as of https://github.com/voxpupuli/puppet-rundeck/commit/571e90449ba0db72f2003e728823ce88035224a2
(this is included in v4.1.0)
