### ISSUE TITLE
Rundeck jobs

### ISSUE THREAD

**Issue by ibaboo** [voxpupuli/puppet-rundeck#326]
Hi

Firstly apologies for asking a question here. This not a bug 

I have a question with regards to puppet/rundeck. In the module description it says “This module provides a way to manage the installation and configuration of rundeck, it's projects, **jobs** and plugins.” 

Can you please advise how does one manage jobs using this module? I don’t see any examples?

**Comment by wyardley** [comment]
I don't know how most folks do it, we just drop in yaml files into the project (in the role we have that wraps this module), but it looks like the module does also support the SCM import / export plugins, so maybe that would be one option.

**Comment by wyardley** [comment]
ps - #33 (still open) would seem to imply that this isn't actually yet implemented, other than via the SCM plugin. I don't know if it's likely to get implemented unless someone submits a PR, as the original authors are not working on this module anymore.
