### ISSUE TITLE
Type/provider for managing jobs

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-rundeck#33]
We should have a basic way of managing the rundeck jobs using the api:

Here is a gist of roughly how it should work (this can be split into examples):

https://gist.github.com/liamjbennett/741c9139a66198dc38b2

**Comment by SydOps** [comment]
@liamjbennett 
Could you please provide detail or give some comments on how to use it?

**Comment by liamjbennett** [comment]
Yes, this work still remains in a branch for that very reason. Two things that need to be done to get this branch merged in 1) validations and tests 2) documentation.

**Comment by jyaworski** [comment]
@liamjbennett I thought about this. It seems like way too much to specify in YAML/config.

What I did for this was to cron `rd-jobs import` and `rd-jobs export` so I could manage everything in the GUI and store the YAML files generated in a git repo. Something to think about.

**Comment by liamjbennett** [comment]
Interesting. 

I am not 100% sold on the idea of a type/provider because of some of the challenges of that approach. It does, as you point out, some across as a little verbose. This is the reason I have kept the work on a branch.

The problem(s) that it solves for us (we are expimenting with it internally) is that we have some common jobs between projects and some variation is jobs between environments. 

This clearly requires a bit more thought and discussion. I may raise some additional issues (marked as questions) in order to give us space to try and work though some of that discussion.

**Comment by jyaworski** [comment]
I find this issue moot now that the SCM plugin has debuted in 2.6.0.

**Comment by jyaworski** [comment]
@liamjbennett update on this? I have a few open PRs against Rundeck to have better API options for #181.

**Comment by liamjbennett** [comment]
We'be been using it internally for a while. I'm happy to raise a PR so we can at least have the discussion.

**Comment by jyaworski** [comment]
Sounds good to me. The Jenkins module for puppet just added this, actually.

I am still skeptical of my personal use-case for this, given that the SCM plugin exists, but there is definitely a use-case for someone.
