### ISSUE TITLE
Puppet evaluation error in "rundeck::config::resource_source"

### ISSUE THREAD

**Issue by shamil** [voxpupuli/puppet-rundeck#362]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: `5.3.2`
- Ruby: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
- Distribution: `Ubuntu 16.04 LTS`
- Module version: `5.0`

## How to reproduce (e.g Puppet code you use)

do not specify `directory` option when defining `rundeck::config::resource_source` resource.

```puppet
rundeck::config::resource_source { 'test':
    project_name => 'test-project',
    source_type  => 'file'
}
```

## What are you seeing

Puppet evaluation error:

`2017-11-11 11:32:31 +0000 Puppet (err): Evaluation Error: Error while evaluating a Resource Statement, Rundeck::Config::Resource_source[test]: parameter 'directory' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)+$/]] value, got String`

## Any additional information you'd like to impart

1. Default  `directory` value is `/` which is not absolute path according to `Stdlib::Absolutepath`. 
2. If I set to directory something different than `/`, like `/tmp/dummy/unused/dir` it works.
3. When `source_type` is `file` it should not check for the `directory` option. IMO

**Comment by juniorsysadmin** [comment]
@shamil This is sadly a bug in stdlib: https://github.com/puppetlabs/puppetlabs-stdlib/pull/811

**Comment by juniorsysadmin** [comment]
@shamil You will need to use stdlib 4.21.0

**Comment by shamil** [comment]
@juniorsysadmin yep that seems to be it. closing
