### ISSUE TITLE
Support inifile 2.0.0 or above

### ISSUE THREAD

**Issue by danielserrao** [voxpupuli/puppet-rundeck#387]
Hi,

In this moment I'm in a project where we use the module puppetlabs/inifile >2.0.0 and if we use below that it will break a lot of other modules.

I would like to know if you intend to update this module to support a more recent version of inifile.

Thanks.

**Comment by bastelfreak** [comment]
We're already testing against the latest version, we just forgot to update our `metadata.json`. Thanks for the hint, I will do this now.

**Comment by danielserrao** [comment]
Hi bastelfreak,

Thanks for the feedback. We will be waiting for the next release.

**Comment by alexjfisher** [comment]
This is now fixed and released in 5.4.0
