### ISSUE TITLE
Add resourcejson

### ISSUE THREAD

**Issue by felipegules** [voxpupuli/puppet-rundeck#398]
- Puppet: 3.8.7
- Ruby: 2.0.0p648
- Distribution: centos7
- Module version: 5.3.0

## How to reproduce (e.g Puppet code you use)
Add resource_source JSON extension 
resource_format: 'resourcejson'

## Any additional information you'd like to impart

diff --git a/modules/rundeck/manifests/config/resource_source.pp b/modules/rundeck/manifests/config/resource_source.pp

--- a/modules/rundeck/manifests/config/resource_source.pp
+++ b/modules/rundeck/manifests/config/resource_source.pp
@@ -81,7 +81,7 @@ define rundeck::config::resource_source(
   String $mapping_params                                         = '',
   Integer $number                                                = 1,
   Optional[String] $project_name                                 = undef,
-  Enum['resourcexml', 'resourceyaml'] $resource_format           = $rundeck::params::resource_format,
+  Enum['resourcexml', 'resourceyaml', 'resourcejson'] $resource_format = $rundeck::params::resource_format,
   Boolean $running_only                                          = true,
   String $script_args                                            = '',
   Boolean $script_args_quoted                                    = $rundeck::params::script_args_quoted,
@@ -154,6 +154,9 @@ define rundeck::config::resource_source(
         'resourceyaml': {
           $file_extension = 'yaml'
         }
+        'resourcejson': {
+          $file_extension = 'json'
+        }
         default: {
           err("The rundeck resource model resource_format ${resource_format} is not supported")
         }

**Comment by bastelfreak** [comment]
Hi @felipegules , thanks for creating this issue. Can you create a PR with this code?

**Comment by kenyon** [comment]
Obsoleted by #520.
