### ISSUE TITLE
[FR] Change rundeck-config.erb to key,value iterator only pattern

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/puppet-rundeck#406]
The rundec-config.erb limits the values that can be set to the ones pre-defined. IMHO it would make much more sense to simply use something like this and removing any logic from the templates
```
<%- @config.sort.each do |k,v| -%>
<%= k %> = "<%= v %>"
<%- end -%>
```

**Comment by bastelfreak** [comment]
Hi @TheMeier, thanks for the issue. It's a common pattern to add a Hash as parameter and at the end of the config file, iterate on the hash (but keep the current parameters). Would you like to provide a PR for this?

**Comment by TheMeier** [comment]
Sure. 
There is already such a hash iterator at the end, sadly its called `gui_config` with comment ` Hash of properties for customizing the [Rundeck GUI]`

How a bout deprecating the current parameters?

**Comment by bastelfreak** [comment]
deprecating them would mean a breaking change. I would prefer it to just add a generic hash option where we iterate on.
