### ISSUE TITLE
What about a new module release?

### ISSUE THREAD

**Issue by TheBigfoot** [voxpupuli/puppet-rundeck#423]
Currently the module version is: Version 5.4.0 released Oct 18th 2018

May I suggest to build a new one in order to take into account the last commits?

**Comment by svenbs** [comment]
@alexjfisher, @danifr, @bastelfreak : as you are the last one merge prs and having a verified tag on your commits. Are there any plans on releasing a new version?

**Comment by alexjfisher** [comment]
@svenbs @TheBigfoot Would either of you be interested in opening a [release PR](https://voxpupuli.org/docs/releasing_version/)?

**Comment by danifr** [comment]
I can prepare the PR if no one else volunteers  :) I'll try to do it this weekend
