### ISSUE TITLE
Incorrect configuration key for threadcount

### ISSUE THREAD

**Issue by erik-dekker** [voxpupuli/puppet-rundeck#435]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.9
- Ruby: 2.1.9p490
- Distribution: CentOS 7
- Module version: 5.4.0
- Rundeck version: rundeck-3.0.21.20190424

## How to reproduce (e.g Puppet code you use)

Default install

## What are you seeing

The ERB template contains the following:

```puppet
quartz.props.threadPool.threadCount = "<%= @quartz_job_threadcount %>"
```

This results in the following config in `/etc/rundeck/rundeck-config.groovy`
```
quartz.props.threadPool.threadCount = "25"
```

## What behaviour did you expect instead

According to the [documentation,](https://docs.rundeck.com/docs/administration/maintenance/tuning-rundeck.html#update-rundeck-config) the key for threadCount is supposed to be changed to `quartz.threadPool.threadCount` . This is explained in the following commit of the documentation:

Documentation commit:
https://github.com/rundeck/docs/commit/b3cea42e45edf11c70f10a3f34b72bb748bc60e9

Rundeck issue:
https://github.com/rundeck/docs/issues/44

## Any additional information you'd like to impart

This was not yet fixed in 6.0 release either:
https://github.com/voxpupuli/puppet-rundeck/blob/master/templates/rundeck-config.erb#L67

So it seems there must be a lot of instances silently ignoring this option.

**Comment by Jayfrown** [comment]
It would be great if we could get some feedback, or have this merged - it would be better for the community as a whole if this project remains up-to-date and relevant rather than dividing the community by forking this project.

**Comment by Jayfrown** [comment]
For anyone else affected by this, upon further review we have opted to use the following workaround:

```puppet
Class { 'rundeck':
  rdeck_config_template => 'profile/application/rundeck/rundeck-config.erb'
}
```

And of course we simply copied the vendored `rundeck-config.erb` to `modules/profile/templates/application/rundeck/rundeck-config.erb`, making the necessary adjustments there.

I'm leaving this issue open so it can be fixed upstream.
