### ISSUE TITLE
Support for Rundeck 3.3.x

### ISSUE THREAD

**Issue by dreamblack86** [voxpupuli/puppet-rundeck#452]
Is it generally planned to map the new changes of Rundeck 3.3.x with this module or does the support end with Rundeck 3.2.x ?
https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.html

Thanks

**Comment by shamil** [comment]
I was able to use this module for Rundeck `3.3.x`, although I'm sure not all everything will work as expected, for example logging configuration, which was changed in `3.3.x`.

**Comment by hdep** [comment]
Hi, 
this module doesn't works with rundeck 3.4 the package is not found.

**Comment by koraz0815** [comment]
> 
> 
> Hi,
> this module doesn't works with rundeck 3.4 the package is not found.

Hi,
the repository for rundeck moved.
See also https://github.com/voxpupuli/puppet-rundeck/issues/469
