### ISSUE TITLE
Re-release required

### ISSUE THREAD

**Issue by nkalupahana** [voxpupuli/puppet-rundeck#478]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.11
- Distribution: Ubuntu 16.04
- Module version: 6.0.0

This module hasn't been re-released in a long time -- and currently, the released version still uses bintray, which means that it currently just doesn't work if installed from Forge. The only way to install this package currently is from source. It needs to be re-released in order to be installable normally.

**Comment by hdep** [comment]
Hello,

I agree, last release is from 2019 right ? 
is there anyone from VoxPupuli can say wht is blocking the module in this state ? Maybe we can help a bit !

@root-expert  @bastelfreak  any helps ? 

thank you

Is there anyone on @
