### ISSUE TITLE
Add sensitive option for database_config

### ISSUE THREAD

**Issue by Joris29** [voxpupuli/puppet-rundeck#482]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.25.1
- Ruby: 2.5.9p229
- Distribution: RHEL 8
- Module version: v6.0.0

## How to reproduce (e.g Puppet code you use)

database_config         => {
      'type'            => 'postgresql',
      'url'             => "jdbc:postgresql://${db_host}/${_servername}",
      'username'        => $db_username,
      'password'        => $db_password.unwrap,
      'driverClassName' => 'org.postgresql.Driver',
    },

## What are you seeing
Notice: /Stage[main]/Rundeck::Config::Global::Rundeck_config/File[/etc/rundeck/rundeck-config.groovy]/content:
--- /etc/rundeck/rundeck-config.groovy  2022-01-11 09:02:27.648577738 +0100
+++ /tmp/puppet-file20220111-42398-1beilhv      2022-01-11 09:06:00.912297639 +0100
@@ -12,7 +12,7 @@
   url = "jdbc:postgresql://localhost/rundeck"
   driverClassName = "org.postgresql.Driver"
   username = "my_user"
'-'  password = "my_pass"
'+'  password = "my_password"
   dialect = ""
 }

## What behaviour did you expect instead
Notice: /Stage[main]/Rundeck::Config::Global::Rundeck_config/File[/etc/rundeck/rundeck-config.groovy]/content: value [redacted]

**Comment by root-expert** [comment]
Hello @Joris29 , can you provide a PR to address this issue?

**Comment by Joris29** [comment]
I was more like a request but i'll check if i can provide a PR for it

**Comment by Joris29** [comment]
@root-expert could you take a look at the PR?

**Comment by nosrio** [comment]
Hi! Could someone please review my PR? Regards

**Comment by Joris29** [comment]
@bastelfreak Could someone pls look into this, the issue has be open for quite some time multiple solutions have been provided but no feedback so far.
