### ISSUE TITLE
New installation of rundeck fails

### ISSUE THREAD

**Issue by Fabian1976** [voxpupuli/puppet-rundeck#552]
This parameter:
```
dataSource.dbCreate = update
```
Found on [this](https://github.com/voxpupuli/puppet-rundeck/blob/33879eb96e6ea2125a22c2670ea38c15bc19e017/templates/rundeck-config.properties.epp#L14C1-L14C29) line, is now hard-coded in the module and prevents new installation of rundeck and a postgresql backend.

In the version before this change (v8.0.1), it was a configurable parameter:
```
dataSource {
  dbCreate = "<%= @database_config['dbCreate'] %>"
```

Because of that fixed parameter, new installs of rundeck with Postgresql now generate this error:
```
[2022-09-29T21:22:05,759] ERROR boot.SpringApplication - Application run failed
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
  Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
```

Manually removing this parameter (i've tested this) results in rundeck starting just fine.

Could this parameter be reverted in to a configurable parameter again?

**Comment by Joris29** [comment]
Hello, it is possible to convert this to a configurable parameter again not sure why you are having this issue.

I personally have installed a new rundeck many times and i never had this issue and yes it's a also with a new postgress instance.

This comes from the official rundeck docs:
![image](https://github.com/user-attachments/assets/f71044f0-3be4-4634-93ed-3730d8f06e4e)

So to me it seems more like some kind of upgrade error where a certain column in your DB doesn't exist.

Could you maybe elaborate a bit more.
Puppet version?
Rundeck version?
Steps to reproduce?

**Comment by SmurfEelco** [comment]
Found this where it states it should be none or removed from https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.4.html in either case it should be configurable in my opinion.

- puppet version 8
- module version 9.01
- rundeck version rundeck-4.13.0.20230515-1.noarch

deployed new vm with rhel 8.10 and waited for puppet to finish via hiera yaml (multiple times with same outcome unless datasource.dbCreate is to none or omitted)

**Comment by Joris29** [comment]
I was not aware of that thanks for bringing this up.
It's still strange I didn't have the issue yet but i will investigate and create a PR to make it a parameter again.

Fyi:
Currently running rhel 8.10 with puppet 7 and rundeck 5.6.0

**Comment by Joris29** [comment]
I created a new PR this should fix the issue you are having.
